sonar.projectKey=exist
sonar.projectName=exist
sonar.sourceEncoding=UTF-8

sonar.sources=server/src,client/src
sonar.exclusions=**/__tests__/**,**/*.test.*,client/src/test/**,client/e2e/**

sonar.javascript.lcov.reportPaths=server/coverage/lcov.info,client/coverage/lcov.info
sonar.javascript.node.maxspace=4096
